import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Footer from "@/components/Footer";
import "./globals.css";


const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-kanit",
});


export const metadata: Metadata = {
  title: "Manage task app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.className} `}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
